# Experiment details
EXPName: Nebraska Mead Site
Region: Nebraska
code: NE
Area_of_Interest: ./NE_site/NE_site.shp


# Model configuration
EPICModel: ./model/EPIC2301dt20230820
start_year: 1995
duration: 25
output_types:
  - ACY  # Annual Crop data file
  - DGN  # Daily general output file
log_dir: ./log
output_dir: ./output


# Weather configuration
weather:
  dir: ./weather
  start_date: 1981-01-01
  end_date: 2020-12-31
  offline: false  # if true, weather info is downloaded and saved before runs (To save space leave it false).
  source: daymet  # Default is daymet or edit to custom weather config file path  

# Soil details
soil:
  ssurgo_gdb : ./gSSURGO_KS.gdb
  soil_map: /home/chandrab/GeoEPIC_metadata/SSURGO.tif
  files_dir: ./soil/files

# Info for Sit files
site:
  dir: ./sites
  slope: /home/chandrab/GeoEPIC_metadata/slope_us.tif
  elevation: /home/chandrab/GeoEPIC_metadata/SRTM_1km_US_project.tif
  slope_length: ./soil/NE_slopelen.csv

# OPC directory
opc_dir: ./opc


# Workspace Run Options
run_info: ./info.csv  # Path to Info CSV or SHP file with columns ('SiteID', 'soil', 'opc', 'dly'). Include ('lat', 'lon') for a CSV file.
# Method for selecting specific sites. Ex: Range(0.35, 0.8), Random(0.1), "CNTYFIPS == 8"; "Shape_Area > 6"
select: Random(0.1)
# Number of parallel processes to run. Recommended to be less than the number of CPU cores.
num_of_workers: 40
# Timeout for each simulation run in seconds. Execution is terminated after this timeout.
timeout: 10
