### Site metadata ###

site_name: GeoEPIC
site_description: Python toolkit to run EPIC model
site_url: https://smarsgroup.github.io/geo_epic_win/

repo_url: https://github.com/smarsGroup/geo_epic_win
# edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
- extra.css

theme:
  name: material
  features:
    - announce.dismiss
    # - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  
  palette:
    - scheme: slate
      primary: lime
      accent: lime
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
    
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/geoepic_logo.png
  favicon: assets/geoepic_logo.webp
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - blog
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            summary:
              classes: true
              functions: true
            show_docstring_modules: false
            filters:
              - "!^_"
          paths:
            - src/geoEpic
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting_started/overview.md
    - Installation: getting_started/installation.md
    - Input Files: 
      - Weather: getting_started/weather.md
      - Soil: getting_started/soil.md
      - Crop Management: getting_started/opc.md
      - Site: getting_started/site.md
    - Simulation: getting_started/simulation.md
    - Calibration: getting_started/calibration.md
    # - Earth Engine Utility: getting_started/gee.md
    - License: getting_started/license.md
    - Contributing: getting_started/contributing.md
  - Tutorials:
    - Single Site Simulation: tutorials/single_site_simulation.md
    - Regional Simulation: tutorials/regional_simulation.md
    - Yield Calibration: tutorials/yield_calibration.md
  - Reference: 
    - geoEpic.core: reference/api/core.md
    - geoEpic.io: reference/api/io.md
    - geoEpic.weather: reference/api/weather.md
    - geoEpic.soil: reference/api/soil.md
    # - geoEpic.gee: reference/api/gee.md
    - geoEpic.utils: reference/api/utils.md
    - Command Line Interface: reference/api/api.md
    - utility: reference/api/utils.md
