### Site metadata ###

site_name: GeoEPIC
site_description: Python toolkit to run EPIC model
site_url: https://smarsgroup.github.io/geo_epic_win/

repo_url: https://github.com/smarsGroup/geo_epic_win
# edit_uri: edit/main/docs/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
- extra.css

theme:
  name: material
  features:
    - announce.dismiss
    # - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  
  palette:
    - scheme: slate
      primary: lime
      accent: lime
      toggle:
        icon: material/brightness-2
        name: "Switch to light mode"
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/brightness-5
        name: "Switch to dark mode"
    
  font:
    text: Roboto
    code: Roboto Mono
  logo: pages/assets/geoepic_logo.png
  favicon: pages/assets/geoepic_logo.webp
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - blog
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true
            summary:
              classes: true
              functions: true
            show_docstring_modules: false
            filters:
              - "!^_"
          paths:
            - src/geoEpic
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home: pages/index.md
  - Getting Started:
      - overview: getting_started/overview.md
      - Installation: getting_started/installation.md
      # - EPIC Model: pages/epic.md
      - Input Files: 
          - Weather Module: pages/Weather.md
          - Soil Module: pages/Soil.md
          - Crop Management: pages/OPC.md
      - EPIC Python Interface: pages/EPICModel.md
      - Calibration: pages/calibration.md
      - Earth Engine Utility: pages/gee.md
      - License: pages/LICENSE.md
      - Contributing: pages/Contributing.md
  - Tutorials:
      - Site Simulation: pages/starter_notebook.md
      - Calibration Example: pages/opt.md
      - Creating Site Input Files: pages/runepic.md
      - Spatial Crop Simulations: pages/runepic.md
      - Querying USDA Soil Data Access: pages/runepic.md
  - Reference: 
      - geoEpic.core: pages/api/core.md
      - geoEpic.io: pages/api/io.md
      - geoEpic.weather: pages/api/weather.md
      - geoEpic.soil: pages/api/soil.md
      - geoEpic.gee: pages/api/gee.md
      - geoEpic.utils: pages/api/utils.md
      - Command Line Interface: pages/api/api.md
      - utility: pages/api/utils.md
