### Site metadata ###

site_name: GeoEPIC
site_description: Python toolkit to run EPIC model
site_url: https://smarsgroup.github.io/geo_epic_win/

repo_url: https://github.com/smarsGroup/geo_epic_win

# site_dir: './site'
### Build settings ###

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material
  # custom_dir: custom
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  
  extra_css:
  - extra.css

  palette:
    primary: black
    
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github

# Plugins
plugins:
  - blog
  - mkdocstrings:
      handlers:
        python:
          options:
            # docstring_style: numpy
            show_root_heading: true
            show_source: false
            summary:
              classes: true
              # attributes: true
              # functions: true
              # modules: true
            show_docstring_modules: false
            parameter_headings: true
            filters:
              - "!^_"
          paths:
            - src/geoEpic
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home:
    - Overview: pages/index.md
    - Installation: pages/installation.md
    - License: pages/LICENSE.md
    - Contributing: pages/Contributing.md
  - EPIC Model:
    - Environmental Policy Integrated Climate Model: pages/epic.md
  - Getting Started:
    - Weather Module: pages/weather.md
    - Soil Module: pages/Soil.md
    - Crop Management: pages/OPC.md
    - Earth Engine Utility: pages/gee.md
  - Tutorials:
    - Site Simulation: pages/starter_notebook.md
    - Model Calibration: pages/opt.md
    - Creating Input Files: pages/runepic.md
    - Running an Experiment: pages/runepic.md
  - API: 
    - Command Line Interface: pages/api/api.md
    - geoEpic.core: pages/api/core.md
    - geoEpic.io: pages/api/io.md
    - geoEpic.weather: pages/api/weather.md
    - geoEpic.soil: pages/api/soil.md
    # - utility: pages/api/utils.md
