# Experiment details
EXPName: umstead Site
Region: 
Area_of_Interest: 

# Model configuration
EPICModel: ./model/EPIC1102.exe
start_date: '2000-01-01'
duration: 6
output_types:
  - ACY  # Annual Crop data file
  - DGN  # Daily general output file
log_dir: ./log
output_dir: ./output


# Path to folders containing input files
weather_dir: ./weather
soil_dir: ./soil/files
site_dir: ./sites
opc_dir: ./opc/files


# Workspace Run Options
# Path to CSV file with columns ('SiteID', 'soil', 'opc', 'dly'). 
sites_info: ./info.csv 
# option for selecting specific sites from above info file. Ex: Range(0.35, 0.8), Random(0.1), "CNTYFIPS == 8"; "Shape_Area > 6"
select: Range(0, 1)
# Number of parallel processes to run. Recommended to be less than the number of CPU cores.
num_of_workers: 4
# Timeout for each simulation run in seconds. Execution is terminated after this timeout.
timeout: 30
